language: python

python:
  - "3.4.3"

install:
  - python setup.py install
  - pip install -r requirements.txt  

script:
  - coverage run --source=django_simple_forum  test_runner.py test

after_success:
  coveralls