"""
Django settings for django_simple_forum project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2d&#b_er%(0^c7z9^87_)*y_j3)2fh6e95v7+=*+-k7a9%emv_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    #'compressor',
    'django_simple_forum',
    'sorl.thumbnail',
    #'simple_pagination'
)

MIDDLEWARE = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    #'whitenoise.middleware.WhiteNoiseMiddleware'
)

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#WSGI_APPLICATION = 'wsgi.application'


# Database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'forum',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
MAIL_SENDER = ""
HOST_URL = "127.0.0.1:8000"

#DEFAULT_FROM_EMAIL = 'IEMForum@yahoo.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'AshramForum@gmail.com'
EMAIL_HOST_PASSWORD = 'forumadmin'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')
STATIC_URL = '/static/'

MEDIA_URL = '/pfp/'
MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'pfp')
#GP_CLIENT_ID = "67476397746-73oonbbt08hfjprua8d266a31crcolss.apps.googleusercontent.com"
#GP_CLIENT_SECRET = "a-rA8cPOCfP116liJiaL3K_n"

GP_CLIENT_ID = "377050415674-rfcp78cfrlsjju0tseh3mb3keehvfub2.apps.googleusercontent.com"
GP_CLIENT_SECRET = "BjGoyvdrqurkfy28GFSerjKJ"

FB_APP_ID = "797531267424247"
FB_SECRET = "05b232000a9d5f71aab9cf34470ac85e"


STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
